sonar.organization=quind
sonar.projectKey=quind_tractor-store-frontend
sonar.projectName=Tractor Store Frontend

sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.stories.ts,**/coverage/**

sonar.typescript.lcov.reportPaths=coverage/**/lcov.info

sonar.coverage.exclusions=**/*.spec.ts,**/*.stories.ts,**/test-setup.ts,**/main.ts

sonar.qualitygate.wait=true
